name: seventy_part_apology
description: The 70 part apology of Imam Ali

version: 1.1.0+2005

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^0.5.6
  url_launcher: ^5.4.1
  flutter_launcher_icons: ^0.7.4
  flutter_svg: any

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
     - family: Uthman
       fonts:
         - asset: fonts/hafs.otf
           weight: 400
     - family: Vazir
       fonts:
         - asset: fonts/vazir.ttf

flutter_icons:
  ios: true
  android: true
  image_path_ios: assets/icon.png
  image_path_android: assets/icon.png
  adaptive_icon_background: assets/background.png
  adaptive_icon_foreground: assets/foreground.png
